require('plugins.s-alpha')
require('plugins.s-autosave')
require('plugins.s-blanket')
require('plugins.s-staline')
require('plugins.s-fterm')
require('plugins.s-telescope')
require('plugins.s-treesitter')
